# -*- coding: utf-8 -*-
"""Copy of JEPTAH OGYEFO ACQUAH's project for python and data visualization  shapeai bootcamp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INRPS2Xzwq0O3d3Xx8kHDIczY24qyIma

link=https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv

# **PROBLEM**


Question1: What is the correlation between features in the dataset. and what two features have very strong correlation with the independent variable? Justify with reason

Question2: Which feature has more outliers. Explain with a visualization.

Question3: In which Age group Majority of people have diabetes? Make a visualization to validate your finding.

**MY SOLUTION**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

"""## **QUESTION 1a.** 

**Corellation between Features in the Dataset** 

"""

df.corr()

"""**QUESTION 1b**

**Heatmap Diagram showing the Corellation between Dataset Features**
"""

sns.heatmap(df.corr(),annot=True)

"""## **Conclusion on the Strongest Correlation**

a. Age and Pregnancies are the two features with the strongest correlation.

**Reason**

b. The relationship between two variables is generally considered strong when their correlation value closely approaches 1.00. From the heatmap above, Age and Pregnancies have the highest correlation value of o.54 which closely approaches correlation value 1.00,hence making Age and Pregnancies get the strongest correlation.

****

# **QUESTION 2**
**Boxplot Diagram showing the Outliers of the Features in the Dataset**
"""

sns.boxplot(data=df,width=0.5,)

"""## **Conclusion made from the Boxplot Diagram above**

a. From the boxplot above **Insulin** has the most outliers.

# **QUESTION 3** 

## **A Describtive Table made on the Dataset**
"""

df.describe()

"""## **A Bar Chart of Age against Diabetes Pedigree Function**"""

sns.barplot(x='Age',y='DiabetesPedigreeFunction',data=df,)
plt.title("Bar Chart of Age versus Diabetes Pedigree Function")
plt.xlim(21,None)

"""## **Conclusion made from the Bar Chart above**

From the above bar chart, **Age 56** has the most diabetes pedigree fucntion.
"""